
- hosts: master
  vars:
    centos_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          63343935663864366262393563656162653733613134313830663763343132643962303336353336
          3964343763343836626365626638343766633232396535610a613163336339313632656133666536
          34336237663436323331303530636231326339653763633531303238396265333133383465663661
          6461613831336435300a646438646231626635326561303736343066633435633066306232343736
          3964
  become: yes
  tasks:
    - name: Add the user centos with a primary group of wheel
      user:
        name: centos
        comment: centos user
        password: "{{ centos_password }}"
        #uid: 1040
        group: wheel

    - name: initialize the cluster
      shell: kubeadm init --kubernetes-version=1.11.0 --pod-network-cidr=10.244.0.0/16 >> cluster_initialized.txt
      args:
        chdir: $HOME
        creates: cluster_initialized.txt

    - name: create .kube directory
      become: yes
      become_user: centos
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/centos/.kube/config
        remote_src: yes
        owner: centos

    - name: install Pod network
      become: yes
      become_user: centos
      shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/v0.9.1/Documentation/kube-flannel.yml >> pod_network_setup.txt
      args:
        chdir: $HOME
        creates: pod_network_setup.txt

    - firewalld:
        port: 6443/tcp
        permanent: true
        state: enabled
    - iptables:
        action: append
        chain: INPUT 
        match: state
        ctstate: NEW
        protocol: tcp
        destination_port: 6443
        jump: ACCEPT
      become: yes
    - name: restart iptables
      service: 
        name: iptables
        state: restarted
    - name: restart firewalld
      service: 
        name: firewalld
        state: restarted
